// Code generated by sqlc-name. DO NOT EDIT.
package table


const BlogTable string = "blog"

func BlogColumns() []string {
	return []string { "id","url","contents" }
}

func BlogFullColumnNames() []string {
	return []string { "blog.id","blog.url","blog.contents" }
}

