// Code generated by sqlc-name. DO NOT EDIT.
package table


const BlogCommentTable string = "blog_comment"

func BlogCommentColumns() []string {
	return []string { "id","guid","url","contents" }
}

func BlogCommentFullColumnNames() []string {
	return []string { "blog_comment.id","blog_comment.guid","blog_comment.url","blog_comment.contents" }
}

