// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package table

import ()

type Blog struct {
	ID       int32  `db:"id"`
	Url      string `db:"url"`
	Contents string `db:"contents"`
}

type BlogComment struct {
	ID       int32  `db:"id"`
	Guid     string `db:"guid"`
	Url      string `db:"url"`
	Contents string `db:"contents"`
}

type User struct {
	ID   int32  `db:"id"`
	Guid string `db:"guid"`
	Name string `db:"name"`
}
