// Code generated by sqlc-name. DO NOT EDIT.
package table


const UserTable string = "user"

func UserColumns() []string {
	return []string { "id","guid","name" }
}

func UserFullColumnNames() []string {
	return []string { "user.id","user.guid","user.name" }
}

