-- Code generated by sqlc-crud. DO NOT EDIT.

-- name: InsertBlog :exec
INSERT INTO blog (
	 url, contents
) VALUES (
	 ?, ?
);
-- name: GetBlog :one
SELECT * FROM blog WHERE id = ?;



-- name: DeleteBlog :exec
DELETE FROM blog WHERE id = ?;
