-- Code generated by sqlc-crud. DO NOT EDIT.
ALTER TABLE blog DROP created_at;
ALTER TABLE blog DROP updated_at;
ALTER TABLE blog_comment DROP created_at;
ALTER TABLE user DROP created_at;
ALTER TABLE user DROP updated_at;

